project:
  type: website
  output-dir: docs
  
website:
  title: "Supplement - Germline PVs and cancer mortality"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: final_round.qmd
        text: Main Analyses
      - href: secondary.qmd
        text: Additional analyses
    tools:
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Hofer TP"
execute:
  freeze: auto
format:
  html:
    theme: 
      - cosmo
      - custom_doc.scss
    toc: true
    code-fold: true
    code-summary: "code"
    embed-resources: true
    sidebar:
      collapse-level: 3
      pinned: true
toc: true
bibliography: references.bib
editor: source

