---
title: Additional Analyses
---

Additional analyses were undertaken to see if estimates changed after accounting for,

## Missing data, competing risks and time-varying diagnostic changes

Hazard ratios and 95% confidence intervals are shown from a proportional hazards survival model of mortality. Data includes all tested patients diagnosed with the specified cancers diagnosed in calendar years 2013-2019. Followup is through 1/1/2022. Followup time (time zero) begins at 6 months after diagnosis. Patients tested after 6 months post-diagnosis are not included in the models. Only treatments occurring before the 6 month post diagnosis date are included in the covariates. Data was missing for stage (4.5%) and grade (5.8%) which was imputed using multiple imputation methods. Five imputed sets were created, and model results were combined using Rubin’s procedures *.

Cancer specific deaths are modeled, and deaths from other causes are treated as competing risks, using a competing risk model as per Fine and Gray **. To reflect potential Covid related underreporting, a time-varying covariate is included in all models, indicating time after 1/1/2020.



|   | Breast, Triple Negative |   |   | Breast, HER2+ |   |   | Breast, ER/PR+, HER2- |   |   | Colorectal |   |   | Pancreatic |   |   |
|---------------|----------|-------|-------|---------|-------|-------|---------|--------|-------|-----------|--------|--------|-----------|-------|-------|
|  | HR | Lower | Upper | HR | Lower | Upper | HR | Lower | Upper | HR | Lower | Upper | HR | Lower | Upper |
| Genetic testing result |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Negative (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| ATM | 3.84 | 1.71 | 8.62 | 0.67 | 0.23 | 1.96 | 0.73 | 0.40 | 1.33 | 1.39 | 0.81 | 2.40 | 1.01 | 0.62 | 1.66 |
| CHEK2 | 0.27 | 0.06 | 1.22 | 0.29 | 0.08 | 1.07 | 0.86 | 0.55 | 1.34 | 1.05 | 0.61 | 1.80 | 0.28 | 0.09 | 0.88 |
| PALB2 | 0.74 | 0.43 | 1.28 | 0.95 | 0.22 | 4.08 | 1.26 | 0.79 | 1.99 | 1.41 | 0.93 | 2.16 | 1.56 | 0.88 | 2.77 |
| BRCA 1/2 | 0.66 | 0.54 | 0.81 | 1.18 | 0.74 | 1.88 | 1.23 | 1.03 | 1.48 | 1.60 | 1.05 | 2.42 | 0.70 | 0.52 | 0.95 |
| Lynch Syndrome | 1.95 | 0.92 | 4.14 | 0.00 | 0.00 | 0.00 | 1.96 | 1.02 | 3.77 | 0.63 | 0.45 | 0.88 | 0.61 | 0.19 | 1.97 |
| Other PV | 0.96 | 0.68 | 1.36 | 0.74 | 0.38 | 1.41 | 1.09 | 0.78 | 1.51 | 0.86 | 0.63 | 1.17 | 1.14 | 0.84 | 1.56 |
| VUS only | 1.01 | 0.86 | 1.18 | 0.89 | 0.69 | 1.14 | 0.91 | 0.79 | 1.06 | 0.86 | 0.72 | 1.04 | 1.00 | 0.81 | 1.22 |
| Male (vs. Female) |  |  |  |  |  |  |  |  |  | 1.10 | 0.95 | 1.26 | 1.02 | 0.87 | 1.20 |
| Race and Ethnicity |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Non-Hispanic White (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Black | 1.11 | 0.95 | 1.29 | 1.43 | 1.10 | 1.87 | 1.27 | 1.09 | 1.49 | 1.03 | 0.81 | 1.29 | 1.12 | 0.81 | 1.55 |
| Asian | 0.69 | 0.54 | 0.88 | 1.07 | 0.78 | 1.46 | 0.91 | 0.76 | 1.09 | 1.07 | 0.84 | 1.37 | 1.02 | 0.78 | 1.33 |
| Hispanic | 1.05 | 0.90 | 1.23 | 1.27 | 0.99 | 1.64 | 1.08 | 0.93 | 1.25 | 1.16 | 0.97 | 1.41 | 1.10 | 0.85 | 1.43 |
| Other | 0.39 | 0.16 | 0.94 | 0.68 | 0.17 | 2.68 | 0.83 | 0.43 | 1.62 | 1.15 | 0.37 | 3.61 | 1.06 | 0.46 | 2.46 |
| Age at Diagnosis (decades) | 0.99 | 0.94 | 1.05 | 1.10 | 1.01 | 1.20 | 1.22 | 1.17 | 1.28 | 1.14 | 1.07 | 1.20 | 1.13 | 1.05 | 1.22 |
| Poverty level |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Low (poverty \<10%) (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Medium (poverty 10%-19%) | 0.92 | 0.78 | 1.08 | 1.00 | 0.77 | 1.30 | 1.19 | 1.03 | 1.36 | 0.99 | 0.81 | 1.19 | 1.17 | 0.92 | 1.47 |
| High (poverty \> 20%) | 1.11 | 0.92 | 1.35 | 1.70 | 1.25 | 2.32 | 1.50 | 1.25 | 1.79 | 1.14 | 0.88 | 1.48 | 1.17 | 0.84 | 1.65 |
| Rural (vs Urban) | 1.11 | 0.90 | 1.37 | 0.89 | 0.59 | 1.33 | 0.98 | 0.80 | 1.20 | 1.09 | 0.82 | 1.44 | 0.97 | 0.69 | 1.36 |
| Married (vs Not Married) | 0.97 | 0.87 | 1.10 | 0.82 | 0.68 | 1.00 | 0.80 | 0.72 | 0.88 | 0.93 | 0.81 | 1.07 | 0.91 | 0.76 | 1.09 |
| Year of Diagnosis |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2013 (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2014 | 1.15 | 0.94 | 1.39 | 0.99 | 0.74 | 1.31 | 0.83 | 0.71 | 0.98 | 0.86 | 0.65 | 1.14 | 0.84 | 0.57 | 1.24 |
| 2015 | 1.11 | 0.92 | 1.35 | 0.81 | 0.60 | 1.11 | 0.84 | 0.72 | 0.99 | 0.89 | 0.68 | 1.16 | 0.70 | 0.48 | 1.02 |
| 2016 | 0.88 | 0.71 | 1.08 | 0.89 | 0.64 | 1.25 | 0.77 | 0.64 | 0.93 | 0.63 | 0.48 | 0.82 | 0.65 | 0.45 | 0.93 |
| 2017 | 0.86 | 0.69 | 1.07 | 0.86 | 0.58 | 1.28 | 0.63 | 0.51 | 0.78 | 0.62 | 0.47 | 0.82 | 0.61 | 0.43 | 0.87 |
| 2018 | 0.61 | 0.47 | 0.79 | 0.73 | 0.42 | 1.26 | 0.63 | 0.49 | 0.83 | 0.56 | 0.41 | 0.78 | 0.41 | 0.27 | 0.64 |
| 2019 | 0.47 | 0.34 | 0.66 | 0.73 | 0.38 | 1.41 | 0.55 | 0.40 | 0.76 | 0.28 | 0.19 | 0.43 | 0.32 | 0.19 | 0.53 |
| Stage |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 0 | 0.27 | 0.16 | 0.43 | 0.36 | 0.11 | 1.15 | 0.29 | 0.20 | 0.40 | 1.84 | 0.78 | 4.30 | 0.00 | 0.00 | 0.00 |
| 1 (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | 2.59 | 2.10 | 3.19 | 2.90 | 2.01 | 4.17 | 1.85 | 1.58 | 2.18 | 2.39 | 1.50 | 3.80 | 1.41 | 1.02 | 1.93 |
| 3 | 9.28 | 7.49 | 11.49 | 8.80 | 6.04 | 12.80 | 5.28 | 4.42 | 6.31 | 4.63 | 2.83 | 7.56 | 1.54 | 1.11 | 2.15 |
| 4 | 26.45 | 20.61 | 33.96 | 24.45 | 16.57 | 36.07 | 16.20 | 13.28 | 19.75 | 24.18 | 14.79 | 39.51 | 2.08 | 1.50 | 2.88 |
| Grade |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 1 (ref) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | 1.25 | 0.73 | 2.11 | 0.93 | 0.53 | 1.64 | 1.58 | 1.32 | 1.90 | 1.10 | 0.88 | 1.39 |  |  |  |
| 3 | 1.18 | 0.70 | 1.98 | 1.30 | 0.75 | 2.28 | 3.34 | 2.77 | 4.03 | 1.89 | 1.47 | 2.43 |  |  |  |
| 4 | 1.02 | 0.38 | 2.72 | 0.67 | 0.07 | 6.11 | 1.64 | 0.48 | 5.62 | 1.53 | 1.01 | 2.32 |  |  |  |
| Colon (vs. Rectum) |  |  |  |  |  |  |  |  |  | 1.13 | 0.94 | 1.36 |  |  |  |
| Surgery (Breast) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Lumpectomy |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
| Unilateral mastectomy | 1.77 | 1.47 | 2.13 | 0.58 | 0.42 | 0.80 | 1.33 | 1.13 | 1.57 |  |  |  |  |  |  |
| Bilateral mastectomy | 1.25 | 1.03 | 1.53 | 1.65 | 1.21 | 2.25 | 1.18 | 0.99 | 1.41 |  |  |  |  |  |  |
| Other | 1.52 | 1.15 | 2.01 | 1.62 | 1.16 | 2.25 | 0.99 | 0.76 | 1.28 |  |  |  |  |  |  |
| No surgery | 1.69 | 1.43 | 2.00 | 1.37 | 0.83 | 2.26 | 2.18 | 1.84 | 2.58 |  |  |  |  |  |  |
| Surgery (vs. None) (Non-Breast) |  |  |  |  |  |  |  |  |  | 0.55 | 0.46 | 0.66 | 0.53 | 0.43 | 0.65 |
| Chemotherapy (vs None) | 0.89 | 0.73 | 1.08 | 1.48 | 1.11 | 1.97 | 1.22 | 1.07 | 1.40 | 1.23 | 0.93 | 1.63 | 2.19 | 1.57 | 3.05 |
| Radiation Therapy (vs None) | 1.47 | 1.21 | 1.79 | 0.70 | 0.55 | 0.88 | 0.92 | 0.79 | 1.07 | 1.02 | 0.81 | 1.30 | 0.83 | 0.63 | 1.10 |
| HER2-Directed Therapy (vs None) | 0.96 | 0.71 | 1.30 | 0.63 | 0.49 | 0.80 | 0.98 | 0.75 | 1.26 |  |  |  |  |  |  |
| State: CA (vs. GA) | 0.78 | 0.67 | 0.91 | 0.78 | 0.57 | 1.07 | 0.62 | 0.55 | 0.71 | 0.70 | 0.58 | 0.83 | 0.67 | 0.55 | 0.82 |

\* Rubin, D.B. (1987), Multiple Imputation for Nonresponse in Surveys, New York: John Wiley & Sons, Inc.

** Fine, Jason P., and Robert J. Gray. “A proportional hazards model for the subdistribution of a competing risk.” Journal of the American Statistical Association 94.446 (1999): 496-509.
